version: "3"

services:

  mongodb:
    image: mongo:3.6.17-xenial
    restart: always
    networks: 
      - default
    ports:
     - "27017:27017"

  redis:
    image: redis:6.0-rc2
    restart: always
    networks: 
      - default
    ports:
     - "6379:6379"

  application:
    image: permission-service
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
        

